version: "2"
networks:
  working:
    external: true
services:
  wsqs:
    build: ./server
    volumes:
      - ./server:/work
      - ./data/server:/data
    working_dir: /work
    command: node run.js
    networks:
      - working
  worker_zip:
    build: ./worker_zip
    volumes:
      - ./worker_zip:/work
    working_dir: /work
    command: node run.js
    networks:
      - working
    depends_on:
      - wsqs
  worker_unzip:
    build: ./worker_unzip
    volumes:
      - ./worker_unzip:/work
    working_dir: /work
    command: node run.js
    networks:
      - working
    depends_on:
      - wsqs
  test:
    build: ./test
    volumes:
      - ./test:/work
      - ./data/zip:/zip
    working_dir: /work
#    command: node run.js zip /zip/asv.txt
    command: node run.js unzip /zip/asv.zip
#    command: node run.js unzip /zip/ace-master.zip
#    command: node test_zip_unzip.js /zip/test.txt
    depends_on:
      - wsqs
    networks:
      - working
    depends_on:
      - wsqs
